### PR TITLE
feat: bump mongoose

### PR DESCRIPTION
**Pull request by ghost**
Bump mongoose v5 to v6

BREAKING CHANGE: bump mongoose

### CODE REVIEW

**Comment by adriasala124** [comment]
> Hey @pierissimo. I had to add a ts-ignore to the Schema constructor. The error was this, and didn't know how to fix it: image
> 
> Also in the code from the mongoose package, it complains. I think these are both linter errors but this one is harder to fix since it happens inside the dependency code: image image

Okay looks like using skipLibCheck fixed both issues :)

**Comment by pierissimo** [comment]
@adriasala124 
let's make sure to update the mongoose version in the examples, and also it would be great to run the examples to check if everything's good there

**Comment by pierissimo** [comment]
there may be some problem with the `context` typing, that we use extensively in apps.

Try to put in an example app, this piece of code, it will fail:
```
model.findOne({}, {}, { context: {} }); // context is typed as string, here will be failing

```

**Comment by adriasala124** [comment]
> there may be some problem with the `context` typing, that we use extensively in apps.
> 
> Try to put in an example app, this piece of code, it will fail:
> 
> ```ts
> model.findOne({}, {}, { context: {} }); // context is typed as string, here will be failing
> ```

Hey @pierissimo! As we discussed to avoid collision of our 'context' with the mongoose context I have renamed it to 'davinciCtx'. I know the examples are missing, I have the changes locally but I need to make the release in order to update the dependencies in the examples.

**Comment by pierissimo** [comment]
@adriasala124 that is not needed, just make the builds and link the packages:
```
lerna run build
lerna bootstrap
```

then you can use the new package versions in the examples

**Review by pierissimo — COMMENTED** [review]
looks good, still not 100% sure if davinciCtx is a good naming or is a bit obscure.
`davinciContext` may be a bit clearer?

Let's see what the other reviewers think

**Comment by juanjoseruiz** [comment]
> looks good, still not 100% sure if davinciCtx is a good naming or is a bit obscure. `davinciContext` may be a bit clearer?
> 
> Let's see what the other reviewers think

I also prefer something like 'davinciContext' as is more clear.

@adriasala124 something strange with the coverage, not sure why diff hit is showing that number if we are not affecting coverage.

**Review by pierissimo — APPROVED** [review]

**Review by juanjoseruiz — APPROVED** [review]

**Pull request merged**
