### PR TITLE
feat: support nested required properties in objects

### PR DESCRIPTION
**Pull request by ghost**
Added suport for required inside nested properties like in the example. 
```
class Customer {
	@entity.prop({ 
		required: true, 
		properties: {
			firstName: { type: 'string', required: true },
			middleName: { type: 'string' },
			lastName: { type: 'string', required: true },
			birthday: {
				type: 'object',
				properties: {
					day: { type: 'number', required: true },
					month: { oneOf: ['number', 'string'], required: true },
					year: { type: 'number' }
				}
			}
		}
	})
	personalInfo: Record<string, string>;
}
```

Before, when using the `rawSchemaOpts` this was allowed like this:
```
class Customer {
	@entity.prop({ 
		required: ['firstName', 'lastName'], 
		properties: {
			firstName: { type: 'string' },
			middleName: { type: 'string' },
			lastName: { type: 'string' },
			birthday: {
				type: 'object',
				properties: {
					day: { type: 'number' },
					month: { oneOf: ['number', 'string'] },
					year: { type: 'number' }
				},
				required: ['day', 'month']
			}
		}
	})
	personalInfo: Record<string, string>;
}
```
Now, the required only takes booleans and must be indicated in each of the properties, but the entity definition will translate it into the correct json schema definition.

Reference & examples https://swagger.io/specification/#schema-object

### CODE REVIEW

**Comment by pierissimo** [comment]
it's probably better to support the standard syntax of JSON Schema object, like you mention in the second example.

we should support the following cases and syntaxes:

**Case 1: required as boolean** 
```ts

@entity.prop({ required: true })
firstname: string
```

**Case 2: required as array of property names** 
```ts

@entity.prop({
  properties: { $limit: { type: 'number' }, $skip: { type: 'number' } },
  required: ['$limit']
})
query: Record<string, string>;
```

**Case 3: required as array of property names, nested in objects**
(this should be already supported)
```ts
@entity.prop({
properties: {
	pagination: {
		type: 'object',
		properties: {
			page: { type: 'number' }
		},
		required: ['page']
	}
}
})
query: Record<string, string>;
```

**Comment by adriasala124** [comment]
> it's probably better to support the standard syntax of JSON Schema object, like you mention in the second example.
> 
> we should support the following cases and syntaxes:
> 
> **Case 1: required as boolean**
> 
> ```ts
> @entity.prop({ required: true })
> firstname: string
> ```
> 
> **Case 2: required as array of property names**
> 
> ```ts
> @entity.prop({
>   properties: { $limit: { type: 'number' }, $skip: { type: 'number' } },
>   required: ['$limit']
> })
> query: Record<string, string>;
> ```
> 
> **Case 3: required as array of property names, nested in objects** (this should be already supported)
> 
> ```ts
> @entity.prop({
> properties: {
> 	pagination: {
> 		type: 'object',
> 		properties: {
> 			page: { type: 'number' }
> 		},
> 		required: ['page']
> 	}
> }
> })
> query: Record<string, string>;
> ```

I think the problem with this is that cases 1 & 2 can collide. 
```
@entity.prop({ 
	required: true, 
	properties: {
		firstName: { type: 'string' },
		middleName: { type: 'string' },
		lastName: { type: 'string' }
	}
})
personalInfo: Record<string, string>;
```
In this example if we want to make personalInfo required, as well as firstName and lastName we would have required: true and required: ['firstName', 'lastName'] at the same level.

**Comment by pierissimo** [comment]
I think in that case is better to split up the definition in a dedicated class, there is no reason why all the property definition must be done inline

```ts
@entity.prop({ 
	required: true, 
})
personalInfo: PersonalInfo
```

**Comment by adriasala124** [comment]
> I think in that case is better to split up the definition in a dedicated class, there is no reason why all the property definition must be done inline
> 
> ```ts
> @entity.prop({ 
> 	required: true, 
> })
> personalInfo: PersonalInfo
> ```

Following this reasoning you think it is necessary then to add the required with arrays? The problem could be solved by defining new entities...

**Comment by pierissimo** [comment]
It's definitely not necessary.
But we can support the required prop to be either boolean (for itself) or array of strings (in the case of nested object).
If you want want to define both, it's much better to use a dedicated class, for clarity.

**Comment by adriasala124** [comment]
@pierissimo I implemented the changes as discussed. Also added cases using 'anyOf' with required to check that is working as well.

**Review by pierissimo — APPROVED** [review]
Looks good

**Pull request merged**
